[tool.poetry]
name = "ObjLog"
version = "1.1.1"
description = "Logging, Objectified."
authors = ["Kokonico <kokonico@duck.com>"]
readme = "README.md"
license = "Zlib"
repository = "https://github.com/Kokonico/ObjLog.git"
keywords = ["logging", "object", "objectified", "log", "logger", "loggers", "OOP", "python", "python3", "python3.9", "python3.10", "python3.11", "python3.12"]

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
